
-- data takhfif
-- buffetType
IF NOT EXISTS (SELECT 1 FROM Migrations WHERE version = 'DiscountCoffe-buffetType-Data-v1' 
			)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'SITE_NAME' AND [value] IN ('DiscountCoffe'))
		)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'CUSTOMER_NAME' AND [value] IN ('DiscountCoffe'))
		)
BEGIN

	INSERT INTO DiscountCoffeBuffetTypes (id, title, createdAt, updatedAt)
	VALUES (1, N'کافه', getdate(), getdate())
			,(2, N'رستوران', getdate(), getdate())
			,(3, N'کافه رستوران', getdate(), getdate())
		

	INSERT INTO Migrations(version, createdAt, updatedAt)
	SELECT 'DiscountCoffe-buffetType-Data-v1', GETDATE(), GETDATE()
END

GO

-- buffetcost
IF NOT EXISTS (SELECT 1 FROM Migrations WHERE version = 'DiscountCoffe-buffetCost-Data-v1' 
			)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'SITE_NAME' AND [value] IN ('DiscountCoffe'))
		)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'CUSTOMER_NAME' AND [value] IN ('DiscountCoffe'))
		)
BEGIN

	INSERT INTO DiscountCoffeBuffetCosts (id, title, createdAt, updatedAt)
	VALUES (1, N'دارای آفر', getdate(), getdate())
			,(2, N'اقتصادی', getdate(), getdate())
			,(3, N'شگفت انگیز', getdate(), getdate())
			,(4, N'لاکچری', getdate(), getdate())

	INSERT INTO Migrations(version, createdAt, updatedAt)
	SELECT 'DiscountCoffe-buffetCost-Data-v1', GETDATE(), GETDATE()
END

GO

-- discount coffe options
IF NOT EXISTS (SELECT 1 FROM Migrations WHERE version = 'DiscountCoffe-options-Data-v1' 
			)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'SITE_NAME' AND [value] IN ('DiscountCoffe'))
		)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'CUSTOMER_NAME' AND [value] IN ('DiscountCoffe'))
		)
BEGIN

	INSERT INTO DiscountCoffeOptions(id, title, iconClass,createdAt, updatedAt)
	VALUES (1, N'اسموک روم', 'las la-joint',getdate(), getdate())
			,(2, N'اتاق بازی', 'lni lni-game',getdate(), getdate())
			,(3, N'فضای کودکان', 'lni lni-brush',getdate(), getdate())
			,(4, N'سرو غذا', 'lni lni-dinner',getdate(), getdate())
			,(5, N'برگر', 'lni lni-burger',getdate(), getdate())
			,(6, N'آب میوه', 'lni lni-juice',getdate(), getdate())
			,(7, N'پیتزا', 'lni lni-pizza',getdate(), getdate())
			,(8, N'سلف سرویس', 'lni lni-service',getdate(), getdate())

	INSERT INTO Migrations(version, createdAt, updatedAt)
	SELECT 'DiscountCoffe-options-Data-v1', GETDATE(), GETDATE()
END

GO


--buffetcity
IF NOT EXISTS (SELECT 1 FROM Migrations WHERE version = 'DiscountCoffe-buffetCity-Data-v1' 
			)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'SITE_NAME' AND [value] IN ('DiscountCoffe'))
		)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'CUSTOMER_NAME' AND [value] IN ('DiscountCoffe'))
		)
BEGIN

	INSERT INTO DiscountCoffeCities(id, title, createdAt, updatedAt)
	VALUES 
		(1,N'منطقه 1 - اراج', getdate(), getdate())
		,(2,N'منطقه 1 - ازگل', getdate(), getdate())
		,(3,N'منطقه 1 - امامزاده قاسم', getdate(), getdate())
		,(4,N'منطقه 1 - اوین', getdate(), getdate())
		,(5,N'منطقه 1 - باغ فردوس', getdate(), getdate())
		,(6,N'منطقه 1 - تجریش', getdate(), getdate())
		,(7,N'منطقه 1 - جماران', getdate(), getdate())
		,(8,N'منطقه 1 - چیذر', getdate(), getdate())
		,(9,N'منطقه 1 - حصار بوعلی', getdate(), getdate())
		,(10,N'منطقه 1 - حکمت و دزاشیب', getdate(), getdate())
		,(11,N'منطقه 1 - دارآباد', getdate(), getdate())
		,(12,N'منطقه 1 - دربند', getdate(), getdate())
		,(13,N'منطقه 1 - درکه', getdate(), getdate())
		,(14,N'منطقه 1 - دزاشیب و جوزستان', getdate(), getdate())
		,(15,N'منطقه 1 - رستم آباد', getdate(), getdate())
		,(16,N'منطقه 1 - زعفرانیه', getdate(), getdate())
		,(17,N'منطقه 1 - سوهانک', getdate(), getdate())
		,(18,N'منطقه 1 - شهرک گلها', getdate(), getdate())
		,(19,N'منطقه 1 - شهرک محلاتی', getdate(), getdate())
		,(20,N'منطقه 1 - شهرک نفت', getdate(), getdate())
		,(21,N'منطقه 1 - قیطریه', getdate(), getdate())
		,(22,N'منطقه 1 - کاشانک', getdate(), getdate())
		,(23,N'منطقه 1 - گلاب دره', getdate(), getdate())
		,(24,N'منطقه 1 - محمودیه', getdate(), getdate())
		,(25,N'منطقه 1 - نیاوران', getdate(), getdate())
		,(26,N'منطقه 1 - ولنجک', getdate(), getdate())
		,(27,N'منطقه 2 - آلستوم', getdate(), getdate())
		,(28,N'منطقه 2 - اسلام آباد', getdate(), getdate())
		,(29,N'منطقه 2 - ایوانک', getdate(), getdate())
		,(30,N'منطقه 2 - پاتریس', getdate(), getdate())
		,(31,N'منطقه 2 - پردیسان', getdate(), getdate())
		,(32,N'منطقه 2 - پرواز', getdate(), getdate())
		,(33,N'منطقه 2 - پونک', getdate(), getdate())
		,(34,N'منطقه 2 - توحید', getdate(), getdate())
		,(35,N'منطقه 2 - تهران ویلا', getdate(), getdate())
		,(36,N'منطقه 2 - چوب تراش', getdate(), getdate())
		,(37,N'منطقه 2 - خرم رودی', getdate(), getdate())
		,(38,N'منطقه 2 - درختی', getdate(), getdate())
		,(39,N'منطقه 2 - دریا', getdate(), getdate())
		,(40,N'منطقه 2 - زنجان', getdate(), getdate())
		,(41,N'منطقه 2 - سپهر', getdate(), getdate())
		,(42,N'منطقه 2 - سرو', getdate(), getdate())
		,(43,N'منطقه 2 - سعادت آباد', getdate(), getdate())
		,(44,N'منطقه 2 - شادمهر', getdate(), getdate())
		,(45,N'منطقه 2 - شهرک آزمایش', getdate(), getdate())
		,(46,N'منطقه 2 - شهرک بوعلی', getdate(), getdate())
		,(47,N'منطقه 2 - شهرک غرب', getdate(), getdate())
		,(48,N'منطقه 2 - شهرک مخابرات', getdate(), getdate())
		,(49,N'منطقه 2 - شهرک هما', getdate(), getdate())
		,(50,N'منطقه 2 - صادقیه', getdate(), getdate())
		,(51,N'منطقه 2 - طرشت', getdate(), getdate())
		,(52,N'منطقه 2 - فرحزاد', getdate(), getdate())
		,(53,N'منطقه 2 - کوهسار', getdate(), getdate())
		,(54,N'منطقه 2 - کوی نصر', getdate(), getdate())
		,(55,N'منطقه 2 - مدیریت', getdate(), getdate())
		,(56,N'منطقه 2 - همایون شهر', getdate(), getdate())
		,(57,N'منطقه 3 - آرارات', getdate(), getdate())
		,(58,N'منطقه 3 - ارسباران', getdate(), getdate())
		,(59,N'منطقه 3 - امانیه', getdate(), getdate())
		,(60,N'منطقه 3 - حسن آباد-زرگنده', getdate(), getdate())
		,(61,N'منطقه 3 - داودیه', getdate(), getdate())
		,(62,N'منطقه 3 - درب دوم', getdate(), getdate())
		,(63,N'منطقه 3 - دروس', getdate(), getdate())
		,(64,N'منطقه 3 - رستم آباد - اختیاریه', getdate(), getdate())
		,(65,N'منطقه 3 - قبا', getdate(), getdate())
		,(66,N'منطقه 3 - قلهک', getdate(), getdate())
		,(67,N'منطقه 3 - کاووسیه', getdate(), getdate())
		,(68,N'منطقه 3 - ونک', getdate(), getdate())
		,(69,N'منطقه 4 - اوقاف', getdate(), getdate())
		,(70,N'منطقه 4 - تهران پارس شرقی', getdate(), getdate())
		,(71,N'منطقه 4 - تهران پارس غربی', getdate(), getdate())
		,(72,N'منطقه 4 - جوادیه', getdate(), getdate())
		,(73,N'منطقه 4 - حکیمیه', getdate(), getdate())
		,(74,N'منطقه 4 - خاک سفید', getdate(), getdate())
		,(75,N'منطقه 4 - شمس آباد و مجیدیه', getdate(), getdate())
		,(76,N'منطقه 4 - شمیرا نو', getdate(), getdate())
		,(77,N'منطقه 4 - شهرک ولیعصر و شیان و لویزان', getdate(), getdate())
		,(78,N'منطقه 4 - ضرابخانه و پاسداران', getdate(), getdate())
		,(79,N'منطقه 4 - علم و صنعت', getdate(), getdate())
		,(80,N'منطقه 4 - قاسم آباد و ده نارمک', getdate(), getdate())
		,(81,N'منطقه 4 - قنات کوثر', getdate(), getdate())
		,(82,N'منطقه 4 - کاظم آباد', getdate(), getdate())
		,(83,N'منطقه 4 - کالاد', getdate(), getdate())
		,(84,N'منطقه 4 - کوهسار', getdate(), getdate())
		,(85,N'منطقه 4 - مبارک آباد و حسین آباد', getdate(), getdate())
		,(86,N'منطقه 4 - مجید آباد', getdate(), getdate())
		,(87,N'منطقه 4 - مهران', getdate(), getdate())
		,(88,N'منطقه 4 - نارمک', getdate(), getdate())
		,(89,N'منطقه 5 - المهدی', getdate(), getdate())
		,(90,N'منطقه 5 - اندیشه', getdate(), getdate())
		,(91,N'منطقه 5 - باغ فیض', getdate(), getdate())
		,(92,N'منطقه 5 - بهاران', getdate(), getdate())
		,(93,N'منطقه 5 - پرواز', getdate(), getdate())
		,(94,N'منطقه 5 - پونک جنوبی', getdate(), getdate())
		,(95,N'منطقه 5 - پونک شمالی', getdate(), getdate())
		,(96,N'منطقه 5 - جنت آباد جنوبی', getdate(), getdate())
		,(97,N'منطقه 5 - جنت آباد شمالی', getdate(), getdate())
		,(98,N'منطقه 5 - جنت آباد مرکزی', getdate(), getdate())
		,(99,N'منطقه 5 - حصارک', getdate(), getdate())
		,(100,N'منطقه 5 - سازمان آب', getdate(), getdate())
		,(101,N'منطقه 5 - سازمان برنامه جنوبی', getdate(), getdate())
		,(102,N'منطقه 5 - سازمان برنامه شمالی', getdate(), getdate())
		,(103,N'منطقه 5 - شاهین', getdate(), getdate())
		,(104,N'منطقه 5 - شهر زیبا', getdate(), getdate())
		,(105,N'منطقه 5 - شهران جنوبی', getdate(), getdate())
		,(106,N'منطقه 5 - شهران شمالی', getdate(), getdate())
		,(107,N'منطقه 5 - شهرک آپادانا', getdate(), getdate())
		,(108,N'منطقه 5 - شهرک اکباتان', getdate(), getdate())
		,(109,N'منطقه 5 - شهرک کوهسار', getdate(), getdate())
		,(110,N'منطقه 5 - کن', getdate(), getdate())
		,(111,N'منطقه 5 - کوی ارم', getdate(), getdate())
		,(112,N'منطقه 5 - کوی بیمه', getdate(), getdate())
		,(113,N'منطقه 5 - محله ابوذر', getdate(), getdate())
		,(114,N'منطقه 5 - محله فردوس', getdate(), getdate())
		,(115,N'منطقه 5 - مراد آباد', getdate(), getdate())
		,(116,N'منطقه 5 - مهران', getdate(), getdate())
		,(117,N'منطقه 5 - نفت', getdate(), getdate())
		,(118,N'منطقه 6 - آرژانتین - ساعی', getdate(), getdate())
		,(119,N'منطقه 6 - ایرانشهر', getdate(), getdate())
		,(120,N'منطقه 6 - بهجت آباد', getdate(), getdate())
		,(121,N'منطقه 6 - پارک لاله', getdate(), getdate())
		,(122,N'منطقه 6 - جنت - رفتگر', getdate(), getdate())
		,(123,N'منطقه 6 - دانشگاه تهران', getdate(), getdate())
		,(124,N'منطقه 6 - شریعتی', getdate(), getdate())
		,(125,N'منطقه 6 - شیراز', getdate(), getdate())
		,(126,N'منطقه 6 - عباس آباد', getdate(), getdate())
		,(127,N'منطقه 6 - فاطمی', getdate(), getdate())
		,(128,N'منطقه 6 - قانم مقام- سنائی', getdate(), getdate())
		,(129,N'منطقه 6 - قزل قلعه', getdate(), getdate())
		,(130,N'منطقه 6 - کشاورز غربی', getdate(), getdate())
		,(131,N'منطقه 6 - گاندی', getdate(), getdate())
		,(132,N'منطقه 6 - میدان جهاد', getdate(), getdate())
		,(133,N'منطقه 6 - میدان ولیعصر', getdate(), getdate())
		,(134,N'منطقه 6 - نصرت', getdate(), getdate())
		,(135,N'منطقه 6 - یوسف آباد- امیرآباد', getdate(), getdate())
		,(136,N'منطقه 7 - ارامنه جنوبی', getdate(), getdate())
		,(137,N'منطقه 7 - ارامنه شمالی', getdate(), getdate())
		,(138,N'منطقه 7 - امجدیه- خاقانی', getdate(), getdate())
		,(139,N'منطقه 7 - باغ صبا - سهروردی', getdate(), getdate())
		,(140,N'منطقه 7 - بهار', getdate(), getdate())
		,(141,N'منطقه 7 - حشمتیه', getdate(), getdate())
		,(142,N'منطقه 7 - خواجه نصیر -حقوقی', getdate(), getdate())
		,(143,N'منطقه 7 - خواجه نظام شرقی', getdate(), getdate())
		,(144,N'منطقه 7 - خواجه نظام غربی', getdate(), getdate())
		,(145,N'منطقه 7 - دبستان - مجیدیه', getdate(), getdate())
		,(146,N'منطقه 7 - دهقان', getdate(), getdate())
		,(147,N'منطقه 7 - شارق شرقی', getdate(), getdate())
		,(148,N'منطقه 7 - شارق غربی', getdate(), getdate())
		,(149,N'منطقه 7 - عباس آباد-اندیشه-شهید قندی', getdate(), getdate())
		,(150,N'منطقه 7 - قصر', getdate(), getdate())
		,(151,N'منطقه 7 - کاج', getdate(), getdate())
		,(152,N'منطقه 7 - گرگان', getdate(), getdate())
		,(153,N'منطقه 7 - نظام آباد', getdate(), getdate())
		,(154,N'منطقه 7 - نیلوفر - شهید قندی', getdate(), getdate())
		,(155,N'منطقه 8 - تسلیحات', getdate(), getdate())
		,(156,N'منطقه 8 - تهران پارس', getdate(), getdate())
		,(157,N'منطقه 8 - دردشت', getdate(), getdate())
		,(158,N'منطقه 8 - زرکش', getdate(), getdate())
		,(159,N'منطقه 8 - فدک', getdate(), getdate())
		,(160,N'منطقه 8 - کرمان', getdate(), getdate())
		,(161,N'منطقه 8 - لشکر شرقی', getdate(), getdate())
		,(162,N'منطقه 8 - لشکر غربی', getdate(), getdate())
		,(163,N'منطقه 8 - مجدیه', getdate(), getdate())
		,(164,N'منطقه 8 - مدائن', getdate(), getdate())
		,(165,N'منطقه 8 - نارمک جنوبی', getdate(), getdate())
		,(166,N'منطقه 8 - وحیدیه', getdate(), getdate())
		,(167,N'منطقه 8 - هفت حوض', getdate(), getdate())
		,(168,N'منطقه 9 - استاد معین', getdate(), getdate())
		,(169,N'منطقه 9 - امامزاده عبدالله', getdate(), getdate())
		,(170,N'منطقه 9 - دکترهوشیار', getdate(), getdate())
		,(171,N'منطقه 9 - سرآسیاب مهرآباد', getdate(), getdate())
		,(172,N'منطقه 9 - شمشیری', getdate(), getdate())
		,(173,N'منطقه 9 - شهید دستغیب', getdate(), getdate())
		,(174,N'منطقه 9 - فتح', getdate(), getdate())
		,(175,N'منطقه 9 - فرودگاه', getdate(), getdate())
		,(176,N'منطقه 9 - مهرآباد جنوبی', getdate(), getdate())
		,(177,N'منطقه 10 - بریانک', getdate(), getdate())
		,(178,N'منطقه 10 - زنجان جنوبی', getdate(), getdate())
		,(179,N'منطقه 10 - سرسبیل جنوبی', getdate(), getdate())
		,(180,N'منطقه 10 - سرسبیل شمالی', getdate(), getdate())
		,(181,N'منطقه 10 - سلیمانی- تیموری', getdate(), getdate())
		,(182,N'منطقه 10 - شبیری-جی', getdate(), getdate())
		,(183,N'منطقه 10 - کارون جنوبی', getdate(), getdate())
		,(184,N'منطقه 10 - کارون شمالی', getdate(), getdate())
		,(185,N'منطقه 10 - هاشمی', getdate(), getdate())
		,(186,N'منطقه 10 - هفت چنار', getdate(), getdate())
		,(187,N'منطقه 11 - آذربایجان', getdate(), getdate())
		,(188,N'منطقه 11 - آگاهی', getdate(), getdate())
		,(189,N'منطقه 11 - اسکندری', getdate(), getdate())
		,(190,N'منطقه 11 - امیریه', getdate(), getdate())
		,(191,N'منطقه 11 - انبار نفت', getdate(), getdate())
		,(192,N'منطقه 11 - باغ شاه-میدان حر', getdate(), getdate())
		,(193,N'منطقه 11 - جمالزاده-حشمت الدوله', getdate(), getdate())
		,(194,N'منطقه 11 - جمهوری', getdate(), getdate())
		,(195,N'منطقه 11 - خرم شهر', getdate(), getdate())
		,(196,N'منطقه 11 - راه آهن', getdate(), getdate())
		,(197,N'منطقه 11 - شیخ هادی', getdate(), getdate())
		,(198,N'منطقه 11 - عباسی', getdate(), getdate())
		,(199,N'منطقه 11 - فروزش-امیر بهادر', getdate(), getdate())
		,(200,N'منطقه 11 - فلسطین', getdate(), getdate())
		,(201,N'منطقه 11 - قلمستان-برادران جوادیان', getdate(), getdate())
		,(202,N'منطقه 11 - مخصوص', getdate(), getdate())
		,(203,N'منطقه 11 - منیریه', getdate(), getdate())
		,(204,N'منطقه 11 - هلال احمر', getdate(), getdate())
		,(205,N'منطقه 12 - آبشار', getdate(), getdate())
		,(206,N'منطقه 12 - ارگ - پامنار', getdate(), getdate())
		,(207,N'منطقه 12 - امامزاده یحیی', getdate(), getdate())
		,(208,N'منطقه 12 - ایران', getdate(), getdate())
		,(209,N'منطقه 12 - بازار', getdate(), getdate())
		,(210,N'منطقه 12 - بهارستان', getdate(), getdate())
		,(211,N'منطقه 12 - تختي', getdate(), getdate())
		,(212,N'منطقه 12 - دروازه شمیران', getdate(), getdate())
		,(213,N'منطقه 12 - سنگلج', getdate(), getdate())
		,(214,N'منطقه 12 - شهید هرندی', getdate(), getdate())
		,(215,N'منطقه 12 - فردوسی', getdate(), getdate())
		,(216,N'منطقه 12 - قیام', getdate(), getdate())
		,(217,N'منطقه 12 - کوثر', getdate(), getdate())
		,(218,N'منطقه 13 - آشتیانی', getdate(), getdate())
		,(219,N'منطقه 13 - امامت', getdate(), getdate())
		,(220,N'منطقه 13 - حافظ', getdate(), getdate())
		,(221,N'منطقه 13 - حافظیه', getdate(), getdate())
		,(222,N'منطقه 13 - دهقان', getdate(), getdate())
		,(223,N'منطقه 13 - زاهد گیلانی', getdate(), getdate())
		,(224,N'منطقه 13 - زینبیه', getdate(), getdate())
		,(225,N'منطقه 13 - سرخه حصار', getdate(), getdate())
		,(226,N'منطقه 13 - شورا', getdate(), getdate())
		,(227,N'منطقه 13 - شهید اسدی', getdate(), getdate())
		,(228,N'منطقه 13 - صفا', getdate(), getdate())
		,(229,N'منطقه 13 - قاسم آباد', getdate(), getdate())
		,(230,N'منطقه 13 - نیروی هوایی', getdate(), getdate())
		,(231,N'منطقه 14 - آهنگ', getdate(), getdate())
		,(232,N'منطقه 14 - آهنگران', getdate(), getdate())
		,(233,N'منطقه 14 - ابوذر', getdate(), getdate())
		,(234,N'منطقه 14 - بروجردی', getdate(), getdate())
		,(235,N'منطقه 14 - پرستار', getdate(), getdate())
		,(236,N'منطقه 14 - تاکسیرانی', getdate(), getdate())
		,(237,N'منطقه 14 - جابری', getdate(), getdate())
		,(238,N'منطقه 14 - جوادیه', getdate(), getdate())
		,(239,N'منطقه 14 - چهارصددستگاه', getdate(), getdate())
		,(240,N'منطقه 14 - خاوران', getdate(), getdate())
		,(241,N'منطقه 14 - دژکام', getdate(), getdate())
		,(242,N'منطقه 14 - دولاب', getdate(), getdate())
		,(243,N'منطقه 14 - سیزده آبان', getdate(), getdate())
		,(244,N'منطقه 14 - شاهین', getdate(), getdate())
		,(245,N'منطقه 14 - شکوفه', getdate(), getdate())
		,(246,N'منطقه 14 - شکیب', getdate(), getdate())
		,(247,N'منطقه 14 - شهرابی', getdate(), getdate())
		,(248,N'منطقه 14 - شیوا', getdate(), getdate())
		,(249,N'منطقه 14 - صددستگاه', getdate(), getdate())
		,(250,N'منطقه 14 - فرزانه', getdate(), getdate())
		,(251,N'منطقه 14 - قصر فیروزه', getdate(), getdate())
		,(252,N'منطقه 14 - مینای جنوبی', getdate(), getdate())
		,(253,N'منطقه 14 - مینای شمالی', getdate(), getdate())
		,(254,N'منطقه 14 - نبی اکرم', getdate(), getdate())
		,(255,N'منطقه 14 - نیکنام', getdate(), getdate())
		,(256,N'منطقه 15 - ابوذر', getdate(), getdate())
		,(257,N'منطقه 15 - اتابک', getdate(), getdate())
		,(258,N'منطقه 15 - اسلام آباد - ولفجر', getdate(), getdate())
		,(259,N'منطقه 15 - افسریه بالا', getdate(), getdate())
		,(260,N'منطقه 15 - افسریه پایین', getdate(), getdate())
		,(261,N'منطقه 15 - دهقان', getdate(), getdate())
		,(262,N'منطقه 15 - شوش', getdate(), getdate())
		,(263,N'منطقه 15 - شهرک رضویه', getdate(), getdate())
		,(264,N'منطقه 15 - طیب', getdate(), getdate())
		,(265,N'منطقه 15 - کیان شهر بالا', getdate(), getdate())
		,(266,N'منطقه 15 - کیان شهر پایین', getdate(), getdate())
		,(267,N'منطقه 15 - مسعودیه', getdate(), getdate())
		,(268,N'منطقه 15 - مشیریه', getdate(), getdate())
		,(269,N'منطقه 15 - مطهری', getdate(), getdate())
		,(270,N'منطقه 15 - مظاهری', getdate(), getdate())
		,(271,N'منطقه 15 - مینایی', getdate(), getdate())
		,(272,N'منطقه 15 - ولیعصر', getdate(), getdate())
		,(273,N'منطقه 15 - هاشم آباد', getdate(), getdate())
		,(274,N'منطقه 16 - باغ آذری', getdate(), getdate())
		,(275,N'منطقه 16 - تختي', getdate(), getdate())
		,(276,N'منطقه 16 - جوادیه', getdate(), getdate())
		,(277,N'منطقه 16 - خزانه', getdate(), getdate())
		,(278,N'منطقه 16 - شهرک بعثت', getdate(), getdate())
		,(279,N'منطقه 16 - علی آباد جنوبی', getdate(), getdate())
		,(280,N'منطقه 16 - علی آباد شمالی', getdate(), getdate())
		,(281,N'منطقه 16 - نازی آباد', getdate(), getdate())
		,(282,N'منطقه 16 - یاخچی آباد(رضوان)', getdate(), getdate())
		,(283,N'منطقه 17 - آذری', getdate(), getdate())
		,(284,N'منطقه 17 - امام زاده حسن', getdate(), getdate())
		,(285,N'منطقه 17 - باغ خزانه', getdate(), getdate())
		,(286,N'منطقه 17 - بلورسازی', getdate(), getdate())
		,(287,N'منطقه 17 - جلیلی', getdate(), getdate())
		,(288,N'منطقه 17 - زمزم', getdate(), getdate())
		,(289,N'منطقه 17 - زهتابی', getdate(), getdate())
		,(290,N'منطقه 17 - فلاح', getdate(), getdate())
		,(291,N'منطقه 17 - گلچین', getdate(), getdate())
		,(292,N'منطقه 17 - مقدم', getdate(), getdate())
		,(293,N'منطقه 17 - وصفنارد', getdate(), getdate())
		,(294,N'منطقه 17 - یافت آباد', getdate(), getdate())
		,(295,N'منطقه 18 - بهداشت', getdate(), getdate())
		,(296,N'منطقه 18 - تولید دارو', getdate(), getdate())
		,(297,N'منطقه 18 - حسینی -فردوس', getdate(), getdate())
		,(298,N'منطقه 18 - خلیج فارس جنوبی', getdate(), getdate())
		,(299,N'منطقه 18 - خلیج فارس شمالی', getdate(), getdate())
		,(300,N'منطقه 18 - شاد آباد', getdate(), getdate())
		,(301,N'منطقه 18 - شمس آباد', getdate(), getdate())
		,(302,N'منطقه 18 - شهرک امام خمینی', getdate(), getdate())
		,(303,N'منطقه 18 - شهید رجائی', getdate(), getdate())
		,(304,N'منطقه 18 - صاحب الزمان', getdate(), getdate())
		,(305,N'منطقه 18 - صادقيه', getdate(), getdate())
		,(306,N'منطقه 18 - ولیعصر جنوبی', getdate(), getdate())
		,(307,N'منطقه 18 - ولیعصر شمالی', getdate(), getdate())
		,(308,N'منطقه 18 - هفده شهریور', getdate(), getdate())
		,(309,N'منطقه 18 - یافت آباد جنوبی', getdate(), getdate())
		,(310,N'منطقه 18 - یافت آباد شمالی', getdate(), getdate())
		,(311,N'منطقه 19 - اسفندیاری وبستان', getdate(), getdate())
		,(312,N'منطقه 19 - اسماعیل آباد', getdate(), getdate())
		,(313,N'منطقه 19 - بهمنیار', getdate(), getdate())
		,(314,N'منطقه 19 - خانی آباد نو جنوبی', getdate(), getdate())
		,(315,N'منطقه 19 - خانی آباد نو شمالی', getdate(), getdate())
		,(316,N'منطقه 19 - دولت خواه', getdate(), getdate())
		,(317,N'منطقه 19 - شریعتی جنوبی', getdate(), getdate())
		,(318,N'منطقه 19 - شریعتی شمالی', getdate(), getdate())
		,(319,N'منطقه 19 - شکوفه جنوبی', getdate(), getdate())
		,(320,N'منطقه 19 - شکوفه شمالی', getdate(), getdate())
		,(321,N'منطقه 19 - شهرک احمد خمینی', getdate(), getdate())
		,(322,N'منطقه 19 - شهرک رسالت', getdate(), getdate())
		,(323,N'منطقه 19 - شهید کاظمی', getdate(), getdate())
		,(324,N'منطقه 19 - عبدل آباد', getdate(), getdate())
		,(325,N'منطقه 19 - علی آباد', getdate(), getdate())
		,(326,N'منطقه 19 - قلعه مرغی', getdate(), getdate())
		,(327,N'منطقه 19 - نعمت آباد', getdate(), getdate())
		,(328,N'منطقه 20 - استخر', getdate(), getdate())
		,(329,N'منطقه 20 - اقدسیه', getdate(), getdate())
		,(330,N'منطقه 20 - باروت کوبی', getdate(), getdate())
		,(331,N'منطقه 20 - تقی آبد', getdate(), getdate())
		,(332,N'منطقه 20 - جوانمرد قصاب', getdate(), getdate())
		,(333,N'منطقه 20 - حمزه آباد', getdate(), getdate())
		,(334,N'منطقه 20 - دولت آباد', getdate(), getdate())
		,(335,N'منطقه 20 - دیلمان', getdate(), getdate())
		,(336,N'منطقه 20 - سرتخت', getdate(), getdate())
		,(337,N'منطقه 20 - سیزده آبان', getdate(), getdate())
		,(338,N'منطقه 20 - شهادت', getdate(), getdate())
		,(339,N'منطقه 20 - شهید بهشتی', getdate(), getdate())
		,(340,N'منطقه 20 - شهید غیوری-ابن بابویه', getdate(), getdate())
		,(341,N'منطقه 20 - صفاییه', getdate(), getdate())
		,(342,N'منطقه 20 - ظهیر آباد و ابن بابویه', getdate(), getdate())
		,(343,N'منطقه 20 - علایین', getdate(), getdate())
		,(344,N'منطقه 20 - عیاس آباد', getdate(), getdate())
		,(345,N'منطقه 20 - فیروز آبادی', getdate(), getdate())
		,(346,N'منطقه 20 - منصوریه منگل', getdate(), getdate())
		,(347,N'منطقه 20 - ولی آباد', getdate(), getdate())
		,(348,N'منطقه 20 - هاشم آباد', getdate(), getdate())
		,(349,N'منطقه 21 - باشگاه نفت', getdate(), getdate())
		,(350,N'منطقه 21 - تهرانسر شرقی', getdate(), getdate())
		,(351,N'منطقه 21 - تهرانسر شمالی', getdate(), getdate())
		,(352,N'منطقه 21 - تهرانسر غربی', getdate(), getdate())
		,(353,N'منطقه 21 - تهرانسر مرکزی', getdate(), getdate())
		,(354,N'منطقه 21 - چیتگر جنوبی', getdate(), getdate())
		,(355,N'منطقه 21 - چیتگر شمالی', getdate(), getdate())
		,(356,N'منطقه 21 - شهرک آزادی', getdate(), getdate())
		,(357,N'منطقه 21 - شهرک استقلال', getdate(), getdate())
		,(358,N'منطقه 21 - شهرک پاسداران', getdate(), getdate())
		,(359,N'منطقه 21 - شهرک دانشگاه تهران', getdate(), getdate())
		,(360,N'منطقه 21 - شهرک دریا', getdate(), getdate())
		,(361,N'منطقه 21 - شهرک شهرداری', getdate(), getdate())
		,(362,N'منطقه 21 - شهرک غزالی', getdate(), getdate())
		,(363,N'منطقه 21 - شهرک فرهنگیان', getdate(), getdate())
		,(364,N'منطقه 21 - ورداورد', getdate(), getdate())
		,(365,N'منطقه 21 - ویلا شهر', getdate(), getdate())
		,(366,N'منطقه 22 - آبشار تهران', getdate(), getdate())
		,(367,N'منطقه 22 - پژوهش شمالي', getdate(), getdate())
		,(368,N'منطقه 22 - چيتگر - آزاد شهر', getdate(), getdate())
		,(369,N'منطقه 22 - دهکده المپيک', getdate(), getdate())
		,(370,N'منطقه 22 - زيبادشت', getdate(), getdate())
		,(371,N'منطقه 22 - شهرک شهيد خرازي', getdate(), getdate())
		,(372,N'منطقه 22 - شهرک صدرا', getdate(), getdate())
		,(373,N'منطقه 22 - گلستان شرقي', getdate(), getdate())
		,(374,N'منطقه 22 - گلستان غربي', getdate(), getdate())
	INSERT INTO Migrations(version, createdAt, updatedAt)
	SELECT 'DiscountCoffe-buffetCity-Data-v1', GETDATE(), GETDATE()
END

GO


-- reserve status
IF NOT EXISTS (SELECT 1 FROM Migrations WHERE version = 'DiscountCoffe-reservestatus-Data-v1' 
			)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'SITE_NAME' AND [value] IN ('DiscountCoffe'))
		)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'CUSTOMER_NAME' AND [value] IN ('DiscountCoffe'))
		)
BEGIN

	INSERT INTO DiscountCoffeReserveStatuses(id, title, createdAt, updatedAt)
	VALUES (1, N'نهایی نشده', getdate(), getdate())
			,(2, N'نهایی شده', getdate(), getdate())

	INSERT INTO Migrations(version, createdAt, updatedAt)
	SELECT 'DiscountCoffe-reservestatus-Data-v1', GETDATE(), GETDATE()
END

GO

-- reserve types
IF NOT EXISTS (SELECT 1 FROM Migrations WHERE version = 'DiscountCoffe-reservetypes-Data-v1' 
			)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'SITE_NAME' AND [value] IN ('DiscountCoffe'))
		)
	AND EXISTS (
		SELECT 1 FROM Settings 
		WHERE ([key] = 'CUSTOMER_NAME' AND [value] IN ('DiscountCoffe'))
		)
BEGIN

	INSERT INTO DiscountCoffeReserveTypes(id, title, createdAt, updatedAt)
	VALUES (1, N'منو آنلاین', getdate(), getdate())
			,(2, N'منو از طریق کافه', getdate(), getdate())

	INSERT INTO Migrations(version, createdAt, updatedAt)
	SELECT 'DiscountCoffe-reservetypes-Data-v1', GETDATE(), GETDATE()
END

GO
