export const STOCK_INVENTORY_QUEUE = 'STOCK_INVENTORY_QUEUE';
export const STOCK_INVENTORY_JOB = 'STOCK_INVENTORY_JOB';

export const STOCK_INVENTORY_REMOVE_QUEUE = 'STOCK_INVENTORY_REMOVE_QUEUE';
export const STOCK_INVENTORY_REMOVE_JOB = 'STOCK_INVENTORY_REMOVE_JOB';

export const STOCK_INVENTORY_UPDATE_QUEUE = 'STOCK_INVENTORY_UPDATE_QUEUE';
export const STOCK_INVENTORY_UPDATE_JOB = 'STOCK_INVENTORY_UPDATE_JOB';
