export const QUERY_NEXT_PAGE_PRODUCT_QUEUE = 'QUERY_NEXT_PAGE_PRODUCT';
export const QUERY_NEXT_PAGE_PRODUCT_JOB = 'QUERY_NEXT_PAGE_PRODUCT_JOB';
export const QUERY_NEXT_PAGE_PRODUCT_WITH_LAT_LON_QUEUE =
  'QUERY_NEXT_PAGE_PRODUCT_WITH_LAT_LON_QUEUE';
export const PRODUCT_VIEW_QUEUE = 'PRODUCT_VIEW_QUEUE';
export const PRODUCT_VIEW_JOB = 'PRODUCT_VIEW_JOB';
