export const SYNC_SELLER_BRAND_QUEUE = 'SYNC_SELLER_BRAND_QUEUE';
export const SYNC_SELLER_PRODUCT_TYPE_QUEUE = 'SYNC_SELLER_PRODUCT_TYPE_QUEUE';
export const SYNC_SELLER_WARRANTY_QUEUE = 'SYNC_SELLER_WARRANTY_QUEUE';
export const SYNC_SELLER_FLOW_PRODUCER = 'SYNC_SELLER_FLOW_PRODUCER';
