export const SYNC_SELLER_BRAND_QUEUE = 'SYNC_SELLER_BRAND_QUEUE';
export const SYNC_SELLER_PRODUCT_TYPE_QUEUE = 'SYNC_SELLER_PRODUCT_TYPE_QUEUE';
export const SYNC_SELLER_WARRANTY_QUEUE = 'SYNC_SELLER_WARRANTY_QUEUE';
export const SYNC_SELLER_FLOW_PRODUCER = 'SYNC_SELLER_FLOW_PRODUCER';
export const SYNC_SELLER_VARIANT_QUEUE = 'SYNC_SELLER_VARIANT_QUEUE';
export const SYNC_SELLER_QUEUE = 'SYNC_SELLER_QUEUE';

export const SELLER_BRAND_OFFSET = 'SELLER_BRAND_OFFSET';
export const SELLER_PRODUCT_TYPE_OFFSET = 'SELLER_PRODUCT_TYPE_OFFSET';
export const SELLER_VARIANT_OFFSET = 'SELLER_VARIANT_OFFSET';
export const SELLER_GUARANTEE_OFFSET = 'SELLER_GUARANTEE_OFFSET';
