import {
  BPMNAction,
  BPMNActionType,
  BPMNActivity,
  BPMNActivityType,
  BPMNCondition,
  BPMNConditionType,
  BPMNInboundAction,
  BPMNNode,
  BPMNNodeCommand,
  BPMNNodeCommandType,
  BPMNNodeCondition,
  BPMNOccurredEvent,
  BPMNOrganization,
  BPMNOrganizationUser,
  BPMNOutboundAction,
  BPMNPROCESS,
  BPMNReferralType,
  BPMNRequest,
  BPMNRequestHistory,
  BPMNRequestOccurredEvent,
  BPMNRequestState,
} from "../models";

export const bpmnModels = [
  BPMNActionType,
  BPMNAction,
  BPMNActionType,
  BPMNActivity,
  BPMNConditionType,
  BPMNActivityType,
  BPMNCondition,
  BPMNInboundAction,
  BPMNNode,
  BPMNNodeCommand,
  BPMNNodeCommandType,
  BPMNNodeCondition,
  BPMNOccurredEvent,
  BPMNOrganization,
  BPMNOutboundAction,
  BPMNPROCESS,
  BPMNReferralType,
  BPMNRequest,
  BPMNRequestHistory,
  BPMNRequestOccurredEvent,
  BPMNRequestState,
  BPMNOrganizationUser,
];
