import {
  Buffet,
  BuffetCity,
  BuffetCost,
  BuffetGallery,
  BuffetIgnoreReserve,
  BuffetMenu,
  BuffetMenuCategory,
  BuffetOption,
  BuffetReserve,
  BuffetReserveDetail,
  BuffetReserveStatus,
  BuffetReserveType,
  BuffetType,
  CoffeOption,
  VW_BuffetReservers,
} from "../models/discount-coffe"; // Import everything from the barrel file

export const discountCoffeEntities = [
  Buffet,
  BuffetCity,
  BuffetCost,
  BuffetGallery,
  BuffetIgnoreReserve,
  BuffetMenu,
  BuffetMenuCategory,
  BuffetOption,
  BuffetReserve,
  BuffetReserveDetail,
  BuffetReserveStatus,
  BuffetReserveType,
  BuffetType,
  CoffeOption,
  VW_BuffetReservers,
];
